name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Verify pnpm
        run: pnpm --version

      - name: Set up Node.js with pnpm
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm check-types

      - name: Lint code
        run: pnpm exec eslint src --ext ts

      - name: Build extension
        run: node esbuild.js --production

      - name: Run tests
        run: pnpm test
